### ISSUE TITLE
项目倒入到高版本的IDEA中编译不过(2020年3月的IDEA)

### ISSUE THREAD

**Issue by SEUCalvin** [bauer-bao/SrcHardCodeOptimizeUtil#1]
java: 无法访问com.intellij.notification.Notification
  错误的类文件: /Applications/IntelliJ IDEA CE.app/Contents/lib/platform-api.jar!/com/intellij/notification/Notification.class
    类文件具有错误的版本 55.0, 应为 52.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by SEUCalvin** [comment]
java: 程序包com.intellij.notification不存在

**Comment by SEUCalvin** [comment]
jdk版本导致的

**Comment by bauer-bao** [comment]
可以在SrcHardCodeOptimizeUtil.iml这个文件中加这行代码，把包引入进来
`<orderEntry type="library" name="com.google.collections:google-collections:0.9" level="project" />`
